from __future__ import annotations

import argparse
import os
from pathlib import Path

from baseline_lab.constants import CONSUMER_GROUP, TOPIC_NAME


def env_flag(name: str) -> bool:
    return os.getenv(name, "false").strip().lower() in {"1", "true", "yes", "on"}


def build_config_text(*, enable_dynatrace: bool, enable_splunk: bool) -> str:
    exporters = ["debug", "file"]
    optional_exporters = ""

    if enable_dynatrace:
        exporters.append("otlphttp/dynatrace")
        optional_exporters += """
  otlphttp/dynatrace:
    endpoint: ${env:DYNATRACE_OTLP_ENDPOINT}
    headers:
      Authorization: Api-Token ${env:DYNATRACE_API_TOKEN}
    timeout: 10s
    compression: gzip
    sending_queue:
      enabled: true
      num_consumers: 4
      queue_size: 2048
    retry_on_failure:
      enabled: true
      initial_interval: 1s
      max_interval: 5s
      max_elapsed_time: 30s
"""

    if enable_splunk:
        exporters.append("splunk_hec")
        optional_exporters += """
  splunk_hec:
    endpoint: ${env:SPLUNK_HEC_ENDPOINT}
    token: ${env:SPLUNK_HEC_TOKEN}
    source: orion-baseline-lab
    sourcetype: _json
    index: ${env:SPLUNK_HEC_INDEX}
    timeout: 10s
    disable_compression: false
    sending_queue:
      enabled: true
      num_consumers: 4
      queue_size: 2048
    retry_on_failure:
      enabled: true
      initial_interval: 1s
      max_interval: 5s
      max_elapsed_time: 30s
"""

    return f"""# Generated by python -m baseline_lab.render_collector_config --output collector/collector.generated.yaml
# Do not edit manually; update baseline_lab/render_collector_config.py instead.
extensions:
  health_check:
    endpoint: 0.0.0.0:13133

receivers:
  kafka:
    brokers:
      - kafka:9092
    topic: {TOPIC_NAME}
    group_id: {CONSUMER_GROUP}
    client_id: orion-baseline-kafka-receiver
    encoding: otlp_proto

processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 256
    spike_limit_mib: 64
  batch:
    send_batch_size: 1024
    timeout: 1s

exporters:
  debug:
    verbosity: detailed
  file:
    path: /var/lib/otelcol/exported-logs.jsonl{optional_exporters}

service:
  extensions: [health_check]
  telemetry:
    logs:
      level: info
    metrics:
      address: 0.0.0.0:8888
  pipelines:
    logs:
      receivers: [kafka]
      processors: [memory_limiter, batch]
      exporters: [{", ".join(exporters)}]
"""


def write_config(output_path: Path, *, enable_dynatrace: bool, enable_splunk: bool) -> Path:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        build_config_text(enable_dynatrace=enable_dynatrace, enable_splunk=enable_splunk),
        encoding="utf-8",
    )
    return output_path


def main() -> int:
    parser = argparse.ArgumentParser(description="Render the OTel Collector config for the baseline lab.")
    parser.add_argument(
        "--output",
        default="collector/collector.generated.yaml",
        help="Path to the generated collector configuration file.",
    )
    args = parser.parse_args()
    output_path = Path(args.output)
    write_config(
        output_path,
        enable_dynatrace=env_flag("ENABLE_DYNATRACE"),
        enable_splunk=env_flag("ENABLE_SPLUNK"),
    )
    print(output_path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
